# All clyde templates are initially configured 
# in this file.
templates:
    - docs:
        description: Sphinx and doxygen generation files
        directory: docs
        include:
            - index.rst
            - Makefile.sphinx: {as: Makefile}
            - conf.py
            - doxyfile
     
    - gitignore:
        description: Gitignore file
        directory: $PWD
        include:
            - gitignore: {as: .gitignore}
 
    - ycm:
        description: YouCompleteMe VIM autocomplete templates
        directory: $PWD
        include:
            - ycm_extra_conf.py: {as: .ycm_extra_conf.py}
     
    - empty-test:
        description: Empty test skeleton
        message: Please update your config.yaml to add a test variant
        variants:
        directory: test
        include:
            - cpputest-empty.cpp: {as: test.cpp}
 
    - quickstart:
        description: Basic clyde package template
        meta-include:
            - docs
            - gitignore
            - ycm
            - hello
    
    - hello:
        description: Basic clyde hello project
        message: Installed basic hello project
        directory: src
        include:
            - hello.cpp

    - rtems-init:
        description: Basic initialization template for STM32F7 BSP
        message: Copied RTEMS initialization for STM32F7. For the F4, fetch rtems-init-f4
        directory: src
        include:
            - rtems_entry_stm32f7.cpp

    - rtems-init-f4:
        description: Basic initialization template for STM32F4 BSP
        message: Copied RTEMS initialization for STM32F4. For the F7, fetch rtems-init
        directory: src
        include:
            - rtems_entry_stm32f4.cpp

    - rtems-quickstart:
        description: RTEMS Top level project with a all files needed to get going fast
        meta-include:
          - docs
          - gitignore
          - ycm
          - rtems-init


